default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("ACTIVE_RECORD_CONNECTION_POOL") { 20 } %>
  connect_timeout: 5
  host: localhost
  variables:
    statement_timeout: 15s
    lock_timeout: 10s

development:
  <<: *default
  database: flash-courier

production:
  <<: *default
  database: flash-courier

test:
  <<: *default
  host: localhost
  database: flash-courier-test
  pool: 1
